CREATE TABLE IF NOT EXISTS orders (
    order_id SERIAL PRIMARY KEY,
    invoice_number VARCHAR(36) UNIQUE NOT NULL,
    total_price DECIMAL(12, 2) NOT NULL,
    status order_status NOT NULL DEFAULT 'pending',
    firstname VARCHAR(32) NOT NULL,
    lastname VARCHAR(32) NOT NULL,
    email VARCHAR(100) NOT NULL,
    phone VARCHAR(16),
    street VARCHAR(100) NOT NULL,
    apt_unit VARCHAR(16),
    state CHAR(2) NOT NULL CHECK (
        state IN (
            'AL',
            'AK',
            'AZ',
            'AR',
            'CA',
            'CO',
            'CT',
            'DE',
            'FL',
            'GA',
            'HI',
            'ID',
            'IL',
            'IN',
            'IA',
            'KS',
            'KY',
            'LA',
            'ME',
            'MD',
            'MA',
            'MI',
            'MN',
            'MS',
            'MO',
            'MT',
            'NE',
            'NV',
            'NH',
            'NJ',
            'NM',
            'NY',
            'NC',
            'ND',
            'OH',
            'OK',
            'OR',
            'PA',
            'RI',
            'SC',
            'SD',
            'TN',
            'TX',
            'UT',
            'VT',
            'VA',
            'WA',
            'WV',
            'WI',
            'WY'
        )
    ),
    zipcode VARCHAR(10) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);